version: '3.8'
services: 
  test-react:
    container_name: test-react-app
    image: dbynar/demo-app:1.0
    ports: 
      - 3000:80
  postgres:
    container_name: postgres_db
    image: postgres:13
    ports:
      - 5432:5432
    environment: 
      - POSTGRES_PASSWORD=my-pwd